### ISSUE TITLE
docs-src vs docs

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gtk-rs.github.io#105]
https://github.com/gtk-rs/gtk-rs.github.io/blob/master/README.md says:
> The documentation in docs-src is not intended to be viewed at the /docs-src/ location. Instead the generated static files (_site/docs-src/*) are merged into the docs repo, keeping a nice urls structure.

but currently we have many links to it: Ex. https://gtk-rs.org/#Using
seems it time to fix it and update docs generation in your https://github.com/gtk-rs/release process.
Note: I not sure how to "generate static files" and https://github.com/gtk-rs/docs/ unusable in Windows so I can do almost nothing yourself.
@GuillaumeGomez can you fix this issue?

**Comment by GuillaumeGomez** [comment]
You mean on rustdoc side or...? :p I intend to fix it in rustdoc, but I'm not sure how yet.

**Comment by EPashkin** [comment]
I meant release process side: after updating docs repo copy all "generated files" from docs-src in it.
It it works fine then we can remove all direct link to "docs-src" so only "docs/*" remains.

**Comment by GuillaumeGomez** [comment]
I'm still not sure to understand what you have in mind, sorry... If you have time and motivation, can you please start a PR for it? If you're stuck, it'll at least give me a better idea of what you want to do.

**Comment by EPashkin** [comment]
Global goal is remove duplicate docs root pages (like https://gtk-rs.org/docs/requirements.html vs https://gtk-rs.org/docs-src/requirements.html)
and `/doc-src/*` links from site (so all links points to https://gtk-rs.org/docs/* only.
Main idea: 
at end `build_docs` refresh site with something like `bundle exec jekyll build`,
then copy all _site/docs-src/* to docs repo

**Comment by killercup** [comment]
I just ran into a 404 where https://gtk-rs.org/docs-src/tutorial/rust_and_gtk links to https://gtk-rs.org/docs-src/requirements instead of <https://gtk-rs.org/docs/requirements>. Quite annoying.

**Comment by GuillaumeGomez** [comment]
The "Quite annoying" was maybe too much but I agree, it's annoying. However, the https://gtk-rs.org/docs/requirements isn't supposed to be used anymore.

**Comment by GuillaumeGomez** [comment]
@killercup Should be fixed by #141.

**Comment by killercup** [comment]
Sorry, all I meant to express was that it took me 15min to find that page that lists these requirements after having seen it some months ago :)

**Comment by GuillaumeGomez** [comment]
We're kinda cleaning up things when we realised gtk had its own. But normally; you shouldn't have this issue anymore. :)

**Comment by jsparber** [comment]
Do we need the separate `docs` repo?

If not, we can insert the generated docs directly into the wepage repo under `docs` and move `docs-src` also to `docs`. Which would keep us the nice url and simplifies things.

Additionally, my suggestion would be to move the docs from the `docs` repo to `/docs/stable` and add unstable docs to the same repo under `/docs/unstable`. This resolves the issue about the different development docs which currently is quite confusing. We have at least the following online docs and there url give no clue for what version they are generated : `https://gtk-rs.org/gtk4-rs/gtk4/`, `htttps://gtk-rs.org/gtk-rs/gtk/`, `https://gtk-rs.org/docs/gtk`

**Comment by sdroege** [comment]
That sounds like a good plan, yes. I don't know what the separate docs repo is good for, maybe @GuillaumeGomez is building things there in magic ways?

**Comment by GuillaumeGomez** [comment]
I don't want the docs to be in the website because they're just way too big. That'd be a mess.

**Comment by sdroege** [comment]
That makes sense

**Comment by sophie-h** [comment]
Looks like all this has been resolved :) docs/ and docs-src/ no longer exist and we have docs for different versions.

**Comment by GuillaumeGomez** [comment]
Indeed!
