### ISSUE TITLE
Example for sourceview::FileLoader

### ISSUE THREAD

**Issue by brackleian** [gtk-rs/gtk-rs.github.io#107]
Examples (non-Rust) elsewhere suggest that you can create a `sourceview::FileLoader` and then invoke `load_async()` on it, which presumably loads the file into your `sourceview::View`. However, the `load_async` function is not implemented for `FileLoader`. Is this an oversight, or have I misinterpreted the way it's all supposed to work? I confess to being a newbie to Rust and to GTK, so I could just be missing something obvious.

**Comment by Cogitri** [comment]
Seems like it's not implemented yet: https://github.com/gtk-rs/sourceview/blob/2c488389fed7e7c30ce56b29fc680daad4ef39b8/src/auto/file_loader.rs#L84

**Comment by sophie-h** [comment]
I think sourceview is now provided by

- https://gitlab.gnome.org/World/Rust/sourceview4-rs
- https://gitlab.gnome.org/World/Rust/sourceview5-rs

So it would be good to reopen there, if it still applies.

**Comment by GuillaumeGomez** [comment]
Closing.
