### ISSUE TITLE
Glade tutorial missing gtk::init

### ISSUE THREAD

**Issue by kelvix** [gtk-rs/gtk-rs.github.io#118]
The tutorial that can be found at https://gtk-rs.org/docs-src/tutorial/glade in regards to Glade does not work out of the box with the dependencies from the home web page

	[dependencies.gtk]
	version = "0.7.0"
	features = ["v3_16"]

	[dependencies.gio]
	version = ""
	features = ["v2_44"]

Attempting to build will yield

	Application exited
	thread 'main' panicked at 'GTK has not been initialized. Call `gtk::init` first.', /home/jgarcia/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.7.0/src/auto/builder.rs:46:9
	note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

`gtk::init();` should be called prior to any use of `Builder`.

**Comment by bilelmoussaoui** [comment]
@GuillaumeGomez another one that can be closed now :)
