### ISSUE TITLE
Link broken on webpage 

### ISSUE THREAD

**Issue by grantshandy** [gtk-rs/gtk-rs.github.io#143]
The link to "http://win32builder.gnome.org/" on the page "https://gtk-rs.org/docs-src/tutorial/cross" does not work anymore.

Is there a place that people can still find this content? because it is stopping a lot of debian-based users from cross-compiling with windows easily.

**Comment by fanninpm** [comment]
Try <http://www.tarnyko.net/dl/gtk.htm>.
