### ISSUE TITLE
Release notes page for 2020-07-04 contains a link to nowhere

### ISSUE THREAD

**Issue by fanninpm** [gtk-rs/gtk-rs.github.io#157]
As [pointed out](https://www.reddit.com/r/rust/comments/hl5778/new_gtkrs_release_new_crates_better_apis/fwwzbe7/) and [clarified](https://www.reddit.com/r/rust/comments/hl5778/new_gtkrs_release_new_crates_better_apis/fwxhni7/) by /u/MachaHack on /r/rust, the following passage in the latest release notes contains a link to nowhere:

> #### `glib-macros`
> 
> There's a new crate `glib-macros` now, which is re-exported by the `glib`
> crate and provides a couple of proc-macros
> 
>   * `#[derive(GBoxed)` for easily deriving a boxed type for any Rust type
>     the implements the `Clone` trait. This can be used to store values of that
>     type in e.g. in `glib::Value`.
>   * `#[derive(GEnum)]` for integer representation Rust enums, which registers
>     GLib type for them and allows to use them e.g. in a `glib::Value`.
>   * `#[gflags]`, which registers a GLib type for bitflags and wraps around the
>     `bitflags` crate. Same as above this can then be used e.g. in a
>     `glib::Value`.
> 
> Check the [documentation](https://gtk-rs.org/docs/glib-macro/) for details about the above.

Is <https://gtk-rs.org/docs/glib-macro/> still being written, or should the link point somewhere else?

**Comment by GuillaumeGomez** [comment]
I should have put https://gtk-rs.org/docs/glib_macros/index.html . I'll update the link, thanks!

**Comment by GuillaumeGomez** [comment]
Should be fixed now.
