### ISSUE TITLE
Link to further resources below homepage example

### ISSUE THREAD

**Issue by Firionus** [gtk-rs/gtk-rs.github.io#161]
I just got Hello World to work on Windows - awesome! Afterwards I looked at the homepage below the example, expecting to find further learning resources. Sadly, I didn't find any. 

I think we should probably put a link to the Tutorial there. This would create a nice flow for new users: They start with a simple example and are then guided to the next learning steps.

**Comment by sophie-h** [comment]
We are prominently featuring the book now instead of a minimal example. That should fix the missing "next learning steps."

**Comment by GuillaumeGomez** [comment]
Closing it then.
