### ISSUE TITLE
The documentation is incoherent and poor

### ISSUE THREAD

**Issue by EdoardoLaGreca** [gtk-rs/gtk-rs.github.io#173]
Some parts of the documentation are incoherent and should be fixed, for example [this page](https://gtk-rs.org/) and [this other page](https://gtk-rs.org/docs/gtk/) show a different way of including gtk as a dependency since one recommends to use a git link while the other shows that including it as a normal depencency should work fine.  
This is just an example and I don't know if there are other incoherent parts.

In addition to that, but not as important, the documentation should be clearer and provide more explainations so that new users can start quickly to use the library without having to suppose how it may works.

Thanks in advance!

**Comment by sophie-h** [comment]
I only found git mentioned for "Using latest, not published version" which totally makes sense to me.

**Comment by EdoardoLaGreca** [comment]
Yes, it's like that. However, if someone wants to figure out how to use the library, he/she may understand that it's suggested to use the latest not published version even though it's less stable than the crates.io releases.
