### ISSUE TITLE
Link to cross compile libraries is bunk

### ISSUE THREAD

**Issue by Barugon** [gtk-rs/gtk-rs.github.io#183]
In the tutorial for [cross compiling Windows from Linux](https://gtk-rs.org/docs-src/tutorial/cross), there is a link to download the mingw-w64-gtk3 libraries from win32builder.gnome.org. However, that site does not exist. Is there another place to get the libraries for distributions other than Arch?

**Comment by sdroege** [comment]
Thanks, I missed that PR.

**Comment by anieuwland** [comment]
No problem. I wasn't sure what the etiquette was regarding notifying people of PRs or not and assumed a notification would be sent somehow. 

That PR also intends to close [this ticket](https://github.com/gtk-rs/gtk-rs.github.io/issues/180).

**Comment by sdroege** [comment]
Best to just write a comment after a week or two without anything happening. It's easy to miss notifications :)
