### ISSUE TITLE
Issue in https://gtk-rs.org/docs-src/tutorial/cross

### ISSUE THREAD

**Issue by InfRandomness** [gtk-rs/gtk-rs.github.io#192]
Hi,

it looks like there is an issue in the cross.md file displayed by https://gtk-rs.org/docs-src/tutorial/cross at the openSUSE part,

it currently shows like that on two different computers, both using firefox 84.0.1
![image](https://user-images.githubusercontent.com/43730933/103955541-c9322780-5146-11eb-8f65-fe2bd2629377.png)

this doesn't match the content in the md file at all,
when visualizing the same file at https://github.com/gtk-rs/gtk-rs.github.io/blob/master/docs-src/tutorial/cross.md, everything is displayed correctly though

**Comment by sdroege** [comment]
@GuillaumeGomez Any ideas?

**Comment by GuillaumeGomez** [comment]
Content not updated yet on github side? No idea otherwise...

**Comment by InfRandomness** [comment]
Well.. this is kinda' weird, the content that's being shown doesn't match any of the two commits I made https://github.com/gtk-rs/gtk-rs.github.io/pull/191

**Comment by GuillaumeGomez** [comment]
Yep, but no idea what's going on... I don't have control over the "publication" of the content unfortunately...

**Comment by InfRandomness** [comment]
That's really weird..

**Comment by GuillaumeGomez** [comment]
Maybe ask the github staff directly? I have no idea otherwise...

**Comment by InfRandomness** [comment]
What's even weirder, as I've just noticed is that at the line 28 "### Fedora" doesn't even seems to show up either ? But at line 19, "### Arch Linux" shows up, and I'm wondering if that's not because there's a carriage return between the line 19 and 17, which is not the case for the line 28 that contains "### Fedora" and for the line 33 "### openSUSE"

**Comment by InfRandomness** [comment]
I really don't think the issue is related to the hosting solution but I think it is related to how the website treats the md file

**Comment by GuillaumeGomez** [comment]
Ok, let me double-check the markdown and try to understand what's going on.

**Comment by InfRandomness** [comment]
This confirms my saying, I added carriage returns between lines containing '### ...' and other lines and run the website locally.
