### ISSUE TITLE
Website overhaul

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs.github.io#204]
I adjusted the design based on gtk-rs/release#138

So far, it seem that everyone would like the design better than the status quo.

There have been some discussion about grey and white. Here are two versions, which both have a darker background than the current gtk-rs.org.

I'm not really happy with the header design. But it would also depend a bit on the final project icon.

- [x] Decide on grey
- [x] Adjust to/add icon
- [x] Replace project list with something having less optical illusions

![1-light](https://user-images.githubusercontent.com/3466497/120531811-52404880-c3df-11eb-8dda-10b5d078c790.png)

----

![1-dark](https://user-images.githubusercontent.com/3466497/120531842-58cec000-c3df-11eb-9faf-685e210f5f47.png)

cc @sdroege @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I obviously prefer the greyer version. But otherwise this is a very welcome improvement, thanks!

Do you have an ETA for the logo btw?

**Comment by sdroege** [comment]
I prefer the brighter version for contrast reasons between the text and background. It seems to be some broken new trend to make everything in washed out colors and little contrast.

A bigger problem that I just noticed is that the "Projects using Gtk-rs" has that optical illusion with dots appearing between the the tiles. A bit like https://www.instructables.com/Optical-Illusion-Mysterious-Black-Dots/

Apart from that: `Gtk-rs`, `gtk-rs`, `GTK-rs`, ...? All lowercase looks nicer to me :man_shrugging:

**Comment by bilelmoussaoui** [comment]
> Apart from that: `Gtk-rs`, `gtk-rs`, `GTK-rs`, ...? All lowercase looks nicer to me man_shrugging

Yes, thanks for bringing this up. There's nothing called Gtk, it's either GTK or gtk. It feels just wrong to have the bindings called Gtk-rs.

**Comment by GuillaumeGomez** [comment]
> I prefer the brighter version for contrast reasons between the text and background. It seems to be some broken new trend to make everything in washed out colors and little contrast.

You have to follow trends old man. :p

> A bigger problem that I just noticed is that the "Projects using Gtk-rs" has that optical illusion with dots appearing between the the tiles. A bit like https://www.instructables.com/Optical-Illusion-Mysterious-Black-Dots/

And now I see them too... Thanks I guess? :stuck_out_tongue_closed_eyes: 

> Apart from that: Gtk-rs, gtk-rs, GTK-rs, ...? All lowercase looks nicer to me man_shrugging

I think we never settled that. I don't like GTK-rs but otherwise I don't mind.

**Comment by sophie-h** [comment]
> Apart from that: `Gtk-rs`, `gtk-rs`, `GTK-rs`, ...? All lowercase looks nicer to me

I would prefer GTK-rs because it look more like a project name to me and not only a crate/repo name.

![download (10)](https://user-images.githubusercontent.com/3466497/120534747-7cdfd080-c3e2-11eb-99a4-322367eb08d1.png)

**Comment by GuillaumeGomez** [comment]
What about putting some shiny effects on the name instead to make it easier to be seen? :)

**Comment by sophie-h** [comment]
I think since the light grey variant is (theoretically) even darker than the current website I would commit the lighter variant. @GuillaumeGomez could change it afterwards and it's no longer my responsibility :laughing:

**Comment by sdroege** [comment]
GTK-rs or gtk-rs I'd say, and I would prefer the first.

For the grey issue, I actually preferred the very first version (which was also grey and not white :P). Maybe we should ask an actual designer about this stuff, or @bilelmoussaoui contrast application ;)

**Comment by sophie-h** [comment]
> or @bilelmoussaoui contrast application ;)

If id didn't messed up the contrasts are okay according to the app. (Otherwise I would have already used that as an argument :p)

**Comment by sophie-h** [comment]
Some ideas floating around

1. Remove "Useful links" (maybe merge remaining useful links into FAQ?)
2. Remove "Tutorial" since it is outdated and replaced by the book
3. Remove example code from start page since it is not tested and duplication with rustdoc and book
4. Advertise book on start page
5. Only list most prominent crates on start page
6. Remove "Documentation" since we have links on the start page
7. Move information about lowest required library version to the corresponding rustdoc pages.

![download (15)](https://user-images.githubusercontent.com/3466497/120559780-efac7400-c401-11eb-9756-f5d6a6939ef8.png)

**Comment by sophie-h** [comment]
> A bigger problem that I just noticed is that the "Projects using Gtk-rs" has that optical illusion with dots appearing between the the tiles

This change fixes it for me. It's also what I had in mind originally, highlight that this is some 'random collection'. Does that work for you?

![download (16)](https://user-images.githubusercontent.com/3466497/120718721-07e7c600-c4ca-11eb-9888-bb9f4f4d5555.png)

**Comment by sdroege** [comment]
Seems good to me, thanks :)

**Comment by GuillaumeGomez** [comment]
Looks pretty nice now!

**Comment by sophie-h** [comment]
What I would like to have to finish the website

1. Decision about the project name
2. Ine sentence on what donations are used for

**Comment by GuillaumeGomez** [comment]
For the 1., we need to vote between GTK-rs and gtk-rs, let's do that tomorrow.

For the 2., this is something we need to discuss once the release is over. I have a few ideas but I want to submit them to the contributors first. This is a tricky question and I only have some leads on how to answer that.

**Comment by sophie-h** [comment]
> this is something we need to discuss

Okay, didn't knew that. Removed it from the list.
