### ISSUE TITLE
Add links to ecosystem crates

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs.github.io#208]
Would probably be useful to link somewhere to https://gitlab.gnome.org/World/Rust/ and gstreamer-rs, and possibly other bindings for GNOME-related libraries on top of gtk-rs.

**Comment by sophie-h** [comment]
## The gtk-rs ecosystem

By now, a number of additional bindings for GObject based libraries exist. While not part of the gtk-rs project, many of them are developed in close collaboration. Notable other projects within the gtk-rs ecosystem are

- [gstreamer-rs: Open source multimedia framework](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs)
- [libhandy-rs: Building blocks for modern adaptive GNOME applications (GTK 3)](https://gitlab.gnome.org/World/Rust/libhandy-rs)
- [libadwaita-rs: Building blocks for modern GNOME applications (GTK 4)](https://gitlab.gnome.org/World/Rust/libadwaita-rs)

More bindings can for example be found as part of the [GNOME GitLab Rust Group](https://gitlab.gnome.org/World/Rust).

**Comment by sdroege** [comment]
Sounds good to me, thanks!
