### ISSUE TITLE
Example on gtk-rs.org should be more complete.

### ISSUE THREAD

**Issue by vi** [gtk-rs/gtk-rs.github.io#21]
I think the snippet should be buildable and runnable out of the box.

Instead of just

``` rust
use gtk::{Button, Window, WindowType};
```

there should be

``` rust
extern crate gtk;
use gtk::{Button, Window, WindowType, Inhibit, WindowExt, ContainerExt, WidgetExt, ButtonExt};
```

or just `use gtk::prelude::*;` repeated from the snippet above.

**Comment by gkoz** [comment]
I suppose we could remove the "Create a window, etc." sentence, which is a bit out context there, and join the two pieces.

**Comment by gkoz** [comment]
Or better yet find a way to just show `basic.rs` from the `examples` repo.

**Comment by Michael-F-Bryan** [comment]
`gtk-rs` is probably one of the best rust libraries for making GUIs, but at the moment the [tutorial] is really bare, it doesn't even have a basic hello world! It might be a good idea to give a bit of a walkthrough of the library and how you can get a simple non-trivial GUI going.

I'm more than happy to flesh out the tutorial and make a PR, but what kind of stuff would be useful for someone who's using `gtk-rs` for the first time? Should I look at a couple of the existing Python/C tutorials for GTK and go from there?

[tutorial]: http://gtk-rs.org/tuto/rust_and_gtk

**Comment by GuillaumeGomez** [comment]
We're a wrapper above the gtk library. So if you don't master gtk, you won't go far with gtk-rs. Also, we have a repository full of examples (I think I mentionned it in the tutorial), adding more examples is fine, but I don't see how we could provide a full gtk tutorial. I'm open to suggestions though, but I don't think it's a good idea. If you really think it's needed, go ahead and open a pr for it and we'll see then.

**Comment by vi** [comment]
> if you don't master gtk, you won't go far with gtk-rs

So users also need to know C to learn GTK, and only then use gtk-rs?

**Comment by GuillaumeGomez** [comment]
No, they can look to the examples repository. For more advanced features, they'll have to however.

**Comment by bilelmoussaoui** [comment]
This can be closed as well.

**Comment by vi** [comment]
https://crates.io/crates/gtk references http://gtk-rs.org/docs/ ("http" [sic]), which is 404.

Note sure where is the example on `gtk-rs.org` now.

**Comment by bilelmoussaoui** [comment]
> https://crates.io/crates/gtk references http://gtk-rs.org/docs/ ("http"!)

This was fixed already

> , which is 404.

That's weird. because the link to https://gtk-rs.org/docs/gtk/ works just fine.

> Not sure where is the example on `gtk-rs.org` now.


There are no more examples on the main website. Especially since we nowdays have bindings of gtk4 as well as gtk3. The examples are in the corresponding docs of gtk3-rs/gtk4-rs. Of course all of that hasn't landed in crates.io yet but soon would be.
