### ISSUE TITLE
Projects using gtk-rs: Add carousel/slideshow

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs.github.io#213]
- Select 3 to 4 apps that are featured with a screenshot (and maybe app icon.)
- Maybe keep the huge list of apps for fun and for broader inspiration. Possibly hidden with some mechanisms that reveals all of them.

**Comment by sophie-h** [comment]
Not really happy. But leaving this here as a start.

![download (30)](https://user-images.githubusercontent.com/3466497/121411340-ce003f00-c963-11eb-9dc8-88094339b7c9.png)

![download (31)](https://user-images.githubusercontent.com/3466497/121411363-d3f62000-c963-11eb-9902-fd3266ea59f0.png)

**Comment by Hofer-Julian** [comment]
Regarding screenshot position.
I expected it to be positioned higher. 
It does make sense though to couple it with "apps using gtk-rs" so the current view is probably fine.

**Comment by sophie-h** [comment]
> Regarding screenshot position.
> I expected it to be positioned higher.

I think it's quite common to place the sponsors at the bottom. I would place it between book and sponsors.

**Comment by sophie-h** [comment]
Still not a designer but what do you think about this? (Includes #208)

The screenshots make everything so nervous to me. But maybe we can create screenshots that are not so jittery.

<details>
<img src="https://user-images.githubusercontent.com/3466497/122289324-e091ef80-cef2-11eb-93ee-f509da3b744a.png"/>
</details>

**Comment by GuillaumeGomez** [comment]
Bigger side button for easier sliding, but otherwise looks good to me!

**Comment by sophie-h** [comment]
Larger buttons

![Screenshot-20210616232404-848x662](https://user-images.githubusercontent.com/3466497/122295840-fd7df100-cef9-11eb-9b9c-daa73cf53a9c.png)

**Comment by GuillaumeGomez** [comment]
Bigger please? :3

Also, how does it look like on mobile?

**Comment by sophie-h** [comment]
> Also, how does it look like on mobile?

I removed the buttons there because you can swipe. (Also it changes the items every 5 seconds.)

<details><summary>iOS</summary>
<img src="https://user-images.githubusercontent.com/3466497/122383384-107cd980-cf6b-11eb-9136-f278b089b85f.PNG"/></details>

**Comment by sophie-h** [comment]
> Bigger please? :3

My final bid xD Note that you also have to have areas to the left and the right of the carousel that activate the buttons. You don't have to hit the symbol to get hover and action.

![image](https://user-images.githubusercontent.com/3466497/122386040-bf221980-cf6d-11eb-9023-8a8db4695129.png)

**Comment by sophie-h** [comment]
- [ ] Should we link the screenshots to the source code as well or to the flathub page?
- [ ] Should we display the apps in random or fixed order?
- [ ] Should I create a PR with the apps suggested above or further discussion?

**Comment by GuillaumeGomez** [comment]
> My final bid xD Note that you also have to have areas to the left and the right of the carousel that activate the buttons. You don't have to hit the symbol to get hover and action.

Oh, interesting. Does hovering those areas have a visual change?

**Comment by sophie-h** [comment]
Implemented in #234
