### ISSUE TITLE
Provide png favicons as well

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs.github.io#219]
Currently we are setting the SVG icon as the favicon which doesn't work for old browsers. We should also provide a 32px/16px PNG fallbacks.

Those will also be useful for the generated docs by rustdoc. It would also be nice to have a 256px variant of the SVG logo so we can use it for the docs as well

**Comment by sophie-h** [comment]
> Currently we are setting the SVG icon as the favicon which doesn't work for old browsers. We should also provide a 32px/16px PNG fallbacks.

True, Safari does not seem to support svg favicons.

> Those will also be useful for the generated docs by rustdoc. It would also be nice to have a 256px variant of the SVG logo so we can use it for the docs as well

You mean a 256px png version?

**Comment by bilelmoussaoui** [comment]
> 
> You mean a 256px png version?

Yes, oups. My bad :p
