### ISSUE TITLE
gtk-rs links to docs-src

### ISSUE THREAD

**Issue by rt-tondilt** [gtk-rs/gtk-rs.github.io#25]
Go to the website, click `Gtk-rs documentation`, click `gtk`, error 404.
As I understand, it should just link to `http://gtk-rs.org/docs/` like everywhere else.

**Comment by GuillaumeGomez** [comment]
Oh damn, well found!

**Comment by EPashkin** [comment]
Actually may be it just wrong link in header. It links to http://gtk-rs.org/docs-src/ instead http://gtk-rs.org/docs/ (but /docs/ has no title)

**Comment by GuillaumeGomez** [comment]
Well, it's fixed now.
