### ISSUE TITLE
fix crate version on homepage

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs.github.io#260]
On the homepage the crate version of gtk4 is 0.2.0, but on crates.io it's 0.3.1.

Is there a way to keep it updated automatically? Maybe adding some crates.io badge like 
![crates.io](https://img.shields.io/crates/v/gtk4.svg)

It's just an image to ```https://img.shields.io/crates/v/gtk4.svg```

**Comment by sophie-h** [comment]
The orange might be a bit off. Some random ideas

![image](https://user-images.githubusercontent.com/3466497/219905018-0ce9404c-8a88-46ca-802f-e2d435048a88.png)
