### ISSUE TITLE
Changes for next version after gtk 0.1.3

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gtk-rs.github.io#35]
Added https://github.com/gtk-rs/sourceview

Fix object properties
https://github.com/gtk-rs/gtk/pull/507
https://github.com/gtk-rs/gio/pull/25

Generate *Ext traits by default and allow disabling them instead (by @sdroege)
https://github.com/gtk-rs/gir/pull/364
https://github.com/gtk-rs/gtk/pull/509
https://github.com/gtk-rs/pango/pull/70
https://github.com/gtk-rs/pango/pull/71
https://github.com/gtk-rs/gio/pull/26

https://github.com/gtk-rs/glib/pull/167 Use g_object_ref_sink() instead of g_object_ref() everywhere (by @sdroege)

Generate global function
https://github.com/gtk-rs/gir/pull/371 (by @sdroege)
https://github.com/gtk-rs/gtk/pull/510
https://github.com/gtk-rs/gtk/pull/512
https://github.com/gtk-rs/gdk/pull/164
https://github.com/gtk-rs/gdk/pull/165
https://github.com/gtk-rs/pango/pull/72
https://github.com/gtk-rs/pango/pull/73
https://github.com/gtk-rs/gio/pull/27
https://github.com/gtk-rs/gio/pull/28
https://github.com/gtk-rs/gio/pull/30
https://github.com/gtk-rs/glib/pull/170

https://github.com/gtk-rs/pango/pull/71 fix xcb features (by @charlesvdv)
https://github.com/gtk-rs/pango/pull/75 Generate Coverage and Renderer structs
https://github.com/gtk-rs/pango/pull/81 add Color generation
https://github.com/gtk-rs/pango/pull/82 Generate new types
https://github.com/gtk-rs/pango/pull/84 Added AttrList
https://github.com/gtk-rs/gtk/pull/541 Use more pango objects

Add glib::BoolError for use as return value of possibly failing functions returning booleans (by @sdroege)
https://github.com/gtk-rs/glib/pull/169
https://github.com/gtk-rs/glib/pull/179
https://github.com/gtk-rs/gtk/pull/523

https://github.com/gtk-rs/glib/pull/171 Add Windows implementations for g_setenv, g_getenv, g_unsetenv and g_get_current_dir (by @sdroege)
https://github.com/gtk-rs/glib/pull/172 Implement FromGlibPtrNone and FromGlibPtrFull for Value (by @sdroege)
https://github.com/gtk-rs/glib/pull/194 Initial GMainLoop/GMainContext bindings (by @sdroege)

Generate gio::Icon, gio::ThemedIcon, gdk::DrawingContext
https://github.com/gtk-rs/gio/pull/29
https://github.com/gtk-rs/gdk/pull/166
https://github.com/gtk-rs/gtk/pull/513

Generate windows specific function names:
https://github.com/gtk-rs/gir/issues/375
https://github.com/gtk-rs/sys/pull/50
https://github.com/gtk-rs/glib/pull/177

Add support for gobject closures
https://github.com/gtk-rs/glib/pull/173
https://github.com/gtk-rs/glib/pull/178

**Breaking change** Implement Value traits inside glib_wrapper!() instead of doing it generically
https://github.com/gtk-rs/glib/pull/196

gsize and fixed length arrays support + enum safety:
https://github.com/gtk-rs/glib/pull/183
https://github.com/gtk-rs/glib/pull/184
https://github.com/gtk-rs/gtk/pull/533
https://github.com/gtk-rs/pango/pull/79
https://github.com/gtk-rs/gio/pull/39
https://github.com/gtk-rs/gdk/pull/171

add property and signal support to trait ObjectExt (by sdroege):
https://github.com/gtk-rs/glib/pull/189 Implement public ObjectExt::set_property() and ::get_property()
https://github.com/gtk-rs/glib/pull/190 Various GObject property changes
https://github.com/gtk-rs/glib/pull/191 Implement ObjectExt::connect() for connecting to arbitrary signals
https://github.com/gtk-rs/glib/pull/192 Implement ObjectExt::emit() for emitting arbitrary signals
https://github.com/gtk-rs/glib/pull/193 Remove now obsolete comment from ObjectExt::set_property()

https://github.com/gtk-rs/gtk/pull/516 Add Into for child properties Option

https://github.com/gtk-rs/gtk/pull/518 Add GtkIMMulticontext and GtkIMContext (by daa84)
https://github.com/gtk-rs/gtk/pull/519 Add PrintContext

https://github.com/gtk-rs/glib/pull/180 Add signal::signal_handler_disconnect()

https://github.com/gtk-rs/gtk/pull/525 Change gtk::Application::new parameter to use Into<Option<&str>> (by jeandudey)

https://github.com/gtk-rs/gio/pull/34 Implement open signal and open function
https://github.com/gtk-rs/gio/pull/37 Generate FileInfo (by hfiguiere)
https://github.com/gtk-rs/gio/pull/38 Generate Notification (by nielsdg)
https://github.com/gtk-rs/gio/pull/39 Enable Application::open() autogeneration again
https://github.com/gtk-rs/gio/pull/40 Tls certificate (by antoyo)
https://github.com/gtk-rs/cairo/pull/136 Fix macOS specific functions (by Znapi)
https://github.com/gtk-rs/cairo/pull/140 Error trait for errors
https://github.com/gtk-rs/gtk/pull/529 Simplify API for RadioButton and RadioMenuItem
https://github.com/gtk-rs/gdk/pull/170 Add remaining GdkAtom constants
https://github.com/gtk-rs/gdk/pull/171 Regenerate with latest GIR and enable Display::store_clipboard()
https://github.com/gtk-rs/gdk/pull/172 gdk_window_fullscreen_on_monitor available since 3.18
https://github.com/gtk-rs/gdk/pull/174 Add missing getters for EventScroll
https://github.com/gtk-rs/gtk/pull/535 ShortcutsWindow available since 3.20
https://github.com/gtk-rs/gtk/pull/537 Generate IconTheme
https://github.com/gtk-rs/gtk/pull/538 New types
https://github.com/gtk-rs/gdk/pull/176 Add Geometry, Use cairo types

@GuillaumeGomez What you think about collecting change log here and close issue on merging release PR?

**Comment by GuillaumeGomez** [comment]
Great idea! It'll make our lives a lot more simple. However I'm working on a script in order to generate this list (and make a release more globally). But meanwhile, this is an excellent idea!

**Comment by EPashkin** [comment]
Closing as new [release](http://gtk-rs.org/blog/2017/08/20/new-release.html) happened.
