### ISSUE TITLE
Move tutorials over to use gtk::Application

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs.github.io#41]
See https://github.com/gtk-rs/examples/issues/140

**Comment by GuillaumeGomez** [comment]
It actually solved a few issues for me on OSX so we should definitely do so!

I'll update them (hopefully) in the week-end.

**Comment by sdroege** [comment]
@nielsdg from the gitter channel said he is working on that, so best to communicate with him

**Comment by GuillaumeGomez** [comment]
I'll wait until saturday anyway and then I can't promise anything! :p

**Comment by bilelmoussaoui** [comment]
The tutorial was dropped in favour of the book, so this can be closed now :)
