### ISSUE TITLE
Reference gnome+gtk blog post

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk-rs.github.io#44]
Considering the rising number of blog posts on both gnome libraries and rust, we should index such content.

At first, let's list them in here and I'll write the page later on.

cc @EPashkin 
cc @sdroege
cc @federicomenaquintero

**Comment by sdroege** [comment]
Also links to applications/crates using gtk-rs and related stuff

**Comment by sdroege** [comment]
Many things on https://people.gnome.org/~federico/blog/
http://smallcultfollowing.com/babysteps/blog/2017/05/02/gnome-class-integrating-rust-and-the-gnome-object-system/
https://coaxion.net/blog/category/rust/

**Comment by EPashkin** [comment]
Agree, links need page on gtk-rs.org

**Comment by GuillaumeGomez** [comment]
It has been added so I suppose it can be closed now.
