### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk-rs.github.io#47]
At this point, I think we should make a logo (nothing fancy). If anyone has a proposition, please feel free to do so! :)

cc @gtk-rs/collaborators

**Comment by EPashkin** [comment]
Sorry, I'm indifferent to the pictures

**Comment by GuillaumeGomez** [comment]
Me too, it's just that I don't like the current organization "logo". I'll have trying to do something. We'll see what comes out of it.

**Comment by GuillaumeGomez** [comment]
Picture selected:
