### ISSUE TITLE
Link broken http://win32builder.gnome.org/

### ISSUE THREAD

**Issue by norru** [gtk-rs/gtk-rs.github.io#87]
http://win32builder.gnome.org/ linked from the "cross-build" tutorial https://github.com/gtk-rs/gtk-rs.github.io/blob/master/tuto/cross.md doesn't respond

If the binaries are not available, perhaps it should be replaced by a link to a tutorial on how to cross-compile gtk too?

**Comment by martinber** [comment]
I think that the distros that have mingw64 packages for GTK+3 are:

- Arch Linux (already explained on tutorials).
- [CentOS/Fedora/Mageia](https://pkgs.org/download/mingw64-gtk3)
- MSYS2

I think the easiest way to cross compile to Windows from a Debian-based distro right now is to use a Docker container of some distribution that has the packages.

I don't know where to find the required packages or how to build them, I guess we can take files from some [MSYS2 package](http://repo.msys2.org/mingw/x86_64/)

**Comment by sophie-h** [comment]
These tutorials no longer exist and are supposed to be replaced by a book chapter.

@GuillaumeGomez close?

**Comment by GuillaumeGomez** [comment]
Closing. :)
