### ISSUE TITLE
Website organization

### ISSUE THREAD

**Issue by martinber** [gtk-rs/gtk-rs.github.io#97]
The website has lots of useful information, but I found it a little hard to navigate, so I'm suggesting some changes.

Right now the locations of every piece of documentation of gtk-rs I could find is:

<details>
  <summary>Site map</summary>
  <p>

- [Website](https://gtk-rs.org/)

    - [Blog: `/blog`](https://gtk-rs.org/blog)

    - [Gtk-rs documentation: `/docs-src/index`](https://gtk-rs.org/docs-src/)

        - [Requirements `/docs-src/requirements`](https://gtk-rs.org/docs-src/requirements.html)

        - Links to documentation on each crate, ([gtk](https://gtk-rs.org/docs/gtk/), [gio](https://gtk-rs.org/docs/gio), etc.)

        - Brief example about and features con `Cargo.toml`, already available on [the `rust_and_gtk` tutorial](https://gtk-rs.org/tuto/rust_and_gtk") and [the `version` tutorial](https://gtk-rs.org/tuto/version)

        - Link to [examples repository](https://github.com/gtk-rs/examples)

        - Link to [official GTK docs](https://www.gtk.org/documentation.php)

    - [Outdated Gtk-rs documentation?: `/docs`](http://gtk-rs.org/docs/)

    - [Tutorial: `/docs-src/tutorial`](https://gtk-rs.org/docs-src/tutorial)

        - Links to each one of the tutorials.

    - [FAQ: `/docs-src/faq`](https://gtk-rs.org/docs-src/faq)

    - [Useful links: `/docs-src/useful-links`](https://gtk-rs.org/docs-src/useful-links)

    - [Contact: `/docs-src/contact`](https://gtk-rs.org/docs-src/contact)

    - [Requirements `/docs-src/requirements`](https://gtk-rs.org/docs-src/requirements.html)

    - Brief tutorial, with information already available on [the `rust_and_gtk` tutorial](https://gtk-rs.org/tuto/rust_and_gtk")

- [gtk crate documentation](https://gtk-rs.org/docs/gtk/)

    - Link to [Outdated Gtk-rs documentation?: `/docs`](http://gtk-rs.org/docs/)

- [Examples repository](https://github.com/gtk-rs/examples)

</p></details>

## Changes I suggest

If you think it's a good idea I'm going to work on these changes

- Move `/docs-src/tutorial` to `/docs-src/tutorial/index` and move `/tuto/*` to `/docs-src/tutorial/`.

- In the [tutorials page](https://gtk-rs.org/docs-src/tutorial) I find it odd that the links to `rust_and_gtk` and `gnome_and_rust` are tutorials just like the ones in the list below. I think that every tutorial should be in some sort of list.

- Below each tutorial there are links to the next tutorial, previous tutorial and the summary but it needs some kind of indication of that. Also it would be better if the links were not hardcoded inside each `.md` file. Can be solved when [this new merged Jekyll feature is released](https://github.com/jekyll/jekyll/issues/5754)

- I found that the examples are good tutorials, also that "Projects using gtk-rs" are good examples too.

    - Move "Projects using gtk-rs" to a separate page.

    - Add links to examples and projects on the [tutorials page](https://gtk-rs.org/docs-src/tutorial) and the [documentation page](https://gtk-rs.org/docs-src)

- I think that the instructions about how to add the dependencies to `Cargo.toml` are on too many places:

    - [Main page: `/index`](https://gtk-rs.org/)

    - [Gtk-rs documentation: `/docs-src/index`](https://gtk-rs.org/docs-src/)

    - [The `rust_and_gtk` tutorial](https://gtk-rs.org/tuto/rust_and_gtk")

    - [The `version` tutorial](https://gtk-rs.org/tuto/version)

    I would remove that brief introduction from `/docs-src/index` and maybe merge the `rust_and_gtk` and `version` tutorial too.

- I don't know the purpose of the [`/docs` page](http://gtk-rs.org/docs/) and the [docs repository](https://github.com/gtk-rs/docs)

**Comment by sophie-h** [comment]
We have removed most of this content from the page. I couldn't find anything that still applies.

@GuillaumeGomez close?

**Comment by GuillaumeGomez** [comment]
Closing. :)
